---
kind: Secret
apiVersion: v1
metadata:
  name: tavily-search-key
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    avp.kubernetes.io/path: "kv/ocp/sno/openshift-gitops/llama-stack-playground"
stringData:
  tavily-search-api-key: <TAVILY_SEARCH_API_KEY>
type: Opaque
