---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-mcp-server-with-rh-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-mcp-server-with-rh-nodejs
  template:
    metadata:
      labels:
        app: github-mcp-server-with-rh-nodejs
    spec:
      containers:
      - name: github-mcp-server-with-rh-nodejs
        image: quay.io/redhat-et/mcp-github:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          npx -y supergateway --stdio "node dist/index.js" --port 8080
        ports:
        - containerPort: 8080
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-credentials-v1
              key: token
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
