---
resources:
  - nfd-cr.yaml
  - nfd-rbac-hack.yaml  # broken in 4.19.1
  - configmap.yaml
  - gpu-cluster-policy.yaml

helmGlobals:
  chartHome: ../../olm

helmCharts:
  - name: olm-v0-chart
    includeCRDs: true
    releaseName: olm-v0-chart
    valuesFile: values-v0.yaml

  - name: olm-v1-chart
    includeCRDs: true
    releaseName: olm-v1-chart
    valuesFile: values-v1.yaml
